### PR TITLE
General cleanup and add nsxiv support

### PR DESCRIPTION
**Pull request by N-R-K**
Changed a bunch of stuff, didn't want to spam 5 different Pull Requests so stuffing them all into one.

Please read the commit msg for explanation.

- - -

Also from a quick glace, I think the entire script can be rewritten in POSIX sh and drop the bash dependency.
Currently, I don't really have time for that but I'll give it a go later when I'm up for it.

### CODE REVIEW

**Comment by nagy135** [comment]
This is exactly what I need to work on, these smarter bash details ...ran through it, looks good. But gotta test first before merge. Also I m currently running wayland branch so gotta merge it there as well. Will reply tommorow prob. I dont feel like rewriting in posix, but feel free to open PR. Thanks!

**Comment by N-R-K** [comment]
One more thing, I saw `jq` inside the script but I don't see it documented as a dependency.

**Comment by nagy135** [comment]
I m just curious what that `check_dep` function actually achieves, because actually calling command and seeing *"command not found: sxiv"* is what tells you whats wrong. Its nice not to see error but that way u dont know whats going on. And then, when we specify *"these are dependencies"* to both **AUR package** or **README.md** then why would we need to check? Then also, why not check for **jq, youtube-dl** maybe even **cat** or other gnu utils, imagine listing 100 dependencies like this on larger project ....am i missing something?  I like the rest of your PR so merge it is ...just curious about your reply.

**Comment by N-R-K** [comment]
> _"command not found: sxiv"_ is what tells you whats wrong.

That will still work. The main reason is to disable _optional_ deps, not core deps. If a core dep is not found, then the expected result should be to just exit with that msg, but if an optional dep is not found then it doesn't make sense to spam stdout with "cmd not found" msges since the script will still function fine.

Also, `:` is basically a command that takes args but does nothing. So that's what we're using here to disable the opt deps.

**Comment by nagy135** [comment]
I understand `:` just your use of it to provide nsxiv support consufed me. I see ...looks like you caught all the optionals. Will update README.md about `jq` dependency (does core functionality for sure) and move it to wayland branch that i m actually using.

**Comment by N-R-K** [comment]
> Will update README.md about `jq` dependency (does core functionality for sure)

:+1:

Also if you have some time, try running [shellcheck](https://github.com/koalaman/shellcheck) (should be available on arch) and fixing some of the warnings. We're planning on linking this repo in [nsxiv-extra](https://github.com/nsxiv/nsxiv-extra) under user scripts.

Since there isn't any necessary bashism from what I've seen, I'll open a PR later sometimes when I'm free on converting the script to be POSIX compliant.

**Pull request merged**
